'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Save,Palette,Languages,Database,LayoutDashboard,LogOut,ShieldCheck,Globe2,Search} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {useSite} from '../site-provider';
import {languages,type SiteSettings,type Language} from '../site-settings';
import {translations} from '../translations';
import Hub from '../workbench';
import HistoricalRegister from '../historical-register';
const blocks={summary:'Historische samenvatting',metrics:'Pilotcijfers',attention:'Opvolging',funnel:'Resultatenfunnel',history:'Historische grafiek',recent:'Recente cases',source:'Bronbestand'};
export default function Admin(){
 const {settings,setSettings,settingsError,settingsLoaded}=useSite();const [draft,setDraft]=useState<SiteSettings>(settings);const [base,setBase]=useState<SiteSettings>(settings);const [tab,setTab]=useState('design');const [language,setLanguage]=useState<Language>('nl');const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [failed,setFailed]=useState(false);const [dirty,setDirty]=useState(false);
 useEffect(()=>{if(!dirty){setDraft(settings);setBase(settings)}},[settings,dirty]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 function change(next:SiteSettings){if(!settingsLoaded||settingsError)return;setDraft(next);setDirty(true);setMessage('')}
 async function save(){if(!settingsLoaded||settingsError)return;setBusy(true);setMessage('');setFailed(false);try{const r=await fetch('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},cache:'no-store',credentials:'same-origin',body:JSON.stringify({...draft,expectedSettings:base})});const data=await r.json() as SiteSettings & {error?:string};if(!r.ok)throw Error(data.error||'Opslaan is niet gelukt.');setSettings(data);setDraft(data);setBase(data);setDirty(false);setMessage('Opgeslagen. De wijzigingen zijn zichtbaar in de Hub. Andere geopende apparaten verversen binnen 20 seconden.')}catch(e){setFailed(true);setMessage(e instanceof Error?e.message:'Opslaan is niet gelukt.')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/logout',{method:'POST'});location.assign('/admin')}
 const keys=[...new Set([...Object.keys(translations),...Object.keys(draft.texts)])].filter(k=>k.toLowerCase().includes(query.toLowerCase())||(draft.texts[k]?.[language]??translations[k]?.[language]??'').toLowerCase().includes(query.toLowerCase()));
 return <div className="admin-page"><header className="admin-header"><a href="/" className="admin-back"><ArrowLeft size={18}/> Naar de Hub</a><div className="admin-header-right"><span className="admin-label"><ShieldCheck size={16}/> Beheerder</span><button onClick={logout} className="action secondary"><LogOut size={16}/> Uitloggen</button></div></header><main className="admin-content"><div className="title-row"><div><span className="eyebrow">VERISURE · BEHEER</span><h1>Jouw Hub. Jouw instellingen.</h1><p>Pas de inhoud en uitstraling aan. Casegegevens blijven de bron voor alle cijfers.</p></div>{['design','texts','blocks'].includes(tab)&&<button onClick={save} disabled={busy||!dirty||!settingsLoaded||!!settingsError} className="action primary"><Save size={17}/>{busy?'Opslaan…':'Wijzigingen opslaan'}{dirty?' *':''}</button>}</div>{!settingsLoaded&&!settingsError&&<p role="status">Instellingen laden…</p>}{settingsError&&<p className="error-banner" role="alert">{settingsError} Instellingen opslaan is geblokkeerd om bestaande gegevens te beschermen.</p>}{message&&<p role={failed?'alert':'status'} className={failed?'error-banner':'notice'}>{message}</p>}<nav className="admin-tabs" aria-label="Beheeronderdelen">{[['design','Vormgeving',Palette],['texts','Teksten & talen',Languages],['blocks','Dashboardblokken',LayoutDashboard],['cases','Live cases',Database],['history','Historische gegevens',Database],['domain','Domein & pitch',Globe2]].map(([id,label,Icon])=>{const I=Icon as typeof Palette;return <button key={String(id)} className={tab===id?'selected':''} onClick={()=>setTab(String(id))}><I size={17}/>{String(label)}</button>})}</nav>
 {tab==='design'&&<div className="admin-grid"><section className="panel admin-card"><h2>Merk & uitstraling</h2><p>HTTPS-links worden gecontroleerd. Wachtwoorden staan nooit in deze instellingen.</p><div className="form-grid">{(['primaryColor','sidebarColor'] as const).map((key,i)=><label className="field" key={key}><span>{i?'Zijbalkkleur':'Actiekleur'}</span><div className="color-control"><input type="color" value={draft[key]} onChange={e=>change({...draft,[key]:e.target.value})}/><code>{draft[key]}</code></div></label>)}</div><label className="field"><span>Logo · HTTPS-afbeeldingslink</span><input type="url" value={draft.logoUrl} onChange={e=>change({...draft,logoUrl:e.target.value})}/></label><label className="field"><span>Bronbestand · HTTPS-link</span><input type="url" value={draft.sourceUrl} onChange={e=>change({...draft,sourceUrl:e.target.value})}/></label><label className="field"><span>Standaardtaal voor nieuwe bezoekers</span><Select value={draft.defaultLanguage} onValueChange={v=>change({...draft,defaultLanguage:v as Language})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(languages).map(([key,value])=><SelectItem key={key} value={key}>{value}</SelectItem>)}</SelectContent></Select></label></section><aside className="panel admin-card"><h2>Voorbeeld</h2><div className="brand-preview" style={{borderTopColor:draft.primaryColor}}><img src={draft.logoUrl} alt="Voorbeeld logo"/><h3>International Move Hub</h3><p>Een consistente uitstraling voor elk land.</p><span className="action" style={{background:draft.primaryColor,color:'white'}}>Actieknop</span><div style={{background:draft.sidebarColor,color:'white',padding:18,borderRadius:12,marginTop:20}}>Zijbalk</div></div><p>De voorbeeldkleuren worden pas voor iedereen actief nadat je opslaat.</p></aside></div>}
 {tab==='texts'&&<section className="panel admin-card"><h2>Alle dashboardteksten per taal</h2><p>Kies een taal en zoek op de originele tekst. Laat variabelen zoals {'{a}'}, {'{b}'} en {'{naam}'} staan. Vrij ingevoerde klantnotities worden niet vertaald.</p><div className="admin-text-tools"><Select value={language} onValueChange={v=>setLanguage(v as Language)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(languages).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select><div className="searchbox"><Search size={17}/><input aria-label="Teksten zoeken" placeholder="Zoek tekst of label" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{keys.length} teksten</span></div><div className="translation-list">{keys.map(key=><label className="translation-row" key={key}><span>{key}</span><textarea rows={key.length>120?3:2} value={draft.texts[key]?.[language]??translations[key]?.[language]??key} onChange={e=>change({...draft,texts:{...draft.texts,[key]:{...draft.texts[key],[language]:e.target.value}}})}/></label>)}</div></section>}
 {tab==='blocks'&&<section className="panel admin-card"><h2>Zichtbare dashboardonderdelen</h2><p>Verborgen blokken bewaren hun gegevens. De landpagina’s en formulieren blijven toegankelijk.</p>{Object.entries(blocks).map(([key,label])=><div className="block-toggle" key={key}><label htmlFor={'block-'+key}>{label}</label><Switch id={'block-'+key} checked={draft.sections[key as keyof typeof blocks]} onCheckedChange={value=>change({...draft,sections:{...draft.sections,[key]:value}})}/></div>)}</section>}
 {tab==='cases'&&<section className="admin-data"><p className="admin-data-note">Maak cases aan of bewerk alle velden via het potlood. Wijzigingen worden direct opgeslagen in de gedeelde database.</p><Hub adminMode/></section>}
 {tab==='history'&&<section className="admin-data"><p className="admin-data-note">Bewerk historische bronregels. Het historische overzicht wordt opnieuw berekend bij het openen van de Hub. Het oorspronkelijke importbestand blijft bewaard.</p><HistoricalRegister admin/></section>}
 {tab==='domain'&&<section className="panel admin-card domain-card"><span className="eyebrow">INTERNE PILOT</span><h2>Klaar om te demonstreren</h2><p>De Hub ondersteunt vier interfacetalen, centrale registratie en opvolging in België, Duitsland en Nederland. De historische basislijn blijft gescheiden van nieuwe pilotresultaten.</p><h3>Eigen domein koppelen</h3><ol><li>Kies een domein of subdomein waarvoor je toestemming en DNS-toegang hebt.</li><li>Laat de domeinkoppeling instellen bij de hosting. Gebruik uitsluitend de daarna verstrekte DNS-records.</li><li>Wacht op domeinverificatie en HTTPS-activatie; controleer daarna login, landpagina’s en exports.</li></ol><p>Er is nog geen eigen domein gekoppeld. Alle interne links gebruiken relatieve paden.</p><h3>Vóór organisatiebrede ingebruikname</h3><ul><li>Laat Verisure IT en privacybeheer hosting, toegangsbeleid en bewaartermijnen beoordelen.</li><li>Vervang gedeelde toegangscodes door persoonlijke accounts of goedgekeurde SSO; er is nu geen individueel gebruikerslogboek.</li><li>De timer volgt de gewenste contactdatum. Zonder contactdatum geldt 24 uur vanaf aanmaken. SALE en CANCEL stoppen de timer; PROGRESS houdt hem actief.</li><li>Wijzig de tijdelijke admincode voordat het portaal breed wordt gedeeld.</li></ul></section>}
 </main></div>
}
