'use client';
import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Download,Search,AlertCircle,Pencil,MapPin} from 'lucide-react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {useSite} from './site-provider';
import {countries} from '@/lib/move-cases';
import type {HistoricalRow as Row} from './history-summary';

function csvCell(value:unknown){let text=String(value??'');if(/^\s*[=+\-@]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"'}
const columns={installationNumber:'Installatienummer',requestDate:'Aanvraagdatum',closedDate:'Sluitdatum',source:'Bron',customerType:'Type klant',result:'Uitkomst',cancelStatus:'Status',daysToClose:'Dagen tot sluiting'} as const;

export default function HistoricalRegister({admin=false}:{admin?:boolean}){
 const {t,locale}=useSite();
 const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [destination,setDestination]=useState('ALL');const [page,setPage]=useState(1);const [edit,setEdit]=useState<Row|null>(null);const [saving,setSaving]=useState(false);const [formError,setFormError]=useState('');const [notice,setNotice]=useState('');
 useEffect(()=>{let active=true;fetch('/api/historical',{cache:'no-store'}).then(async response=>{const data=await response.json() as Row[] & {error?:string};if(!response.ok)throw Error(data.error||'Historische cases laden is niet gelukt.');if(active)setRows(data)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Laden is niet gelukt.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const filtered=useMemo(()=>rows.filter(row=>(destination==='ALL'||(destination==='UNASSIGNED'?!row.destinationCountry:row.destinationCountry===destination))&&`${row.installationNumber} ${row.source} ${row.customerType} ${row.cancelStatus} ${countries[row.destinationCountry]||row.destinationCountry}`.toLowerCase().includes(query.trim().toLowerCase())),[rows,query,destination]);
 const pages=Math.max(1,Math.ceil(filtered.length/20));const visible=filtered.slice((page-1)*20,page*20);const assigned=rows.filter(row=>row.destinationCountry).length;
 const date=(iso:string)=>iso?new Date(iso+'T12:00:00').toLocaleDateString(locale,{day:'2-digit',month:'short',year:'numeric'}):'—';
 function exportCsv(){const keys=[...Object.keys(columns),'destinationCountry'] as (keyof Row)[];const labels={...columns,destinationCountry:'Bestemmingsland'} as Record<keyof Row,string>;const data='\uFEFFsep=;\r\n'+keys.map(key=>csvCell(t(labels[key]))).join(';')+'\r\n'+filtered.map(row=>keys.map(key=>csvCell(key==='destinationCountry'?(countries[row.destinationCountry]||''):row[key])).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='historische-emigratiecases.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function save(e:FormEvent){e.preventDefault();if(!edit)return;setSaving(true);setFormError('');try{const endpoint=admin?'/api/admin/historical':'/api/historical';const body=admin?edit:{id:edit.id,destinationCountry:edit.destinationCountry};const response=await fetch(endpoint,{method:admin?'PUT':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json() as Row & {error?:string};if(!response.ok)throw Error(data.error||'Opslaan is niet gelukt.');setRows(current=>current.map(row=>row.id===data.id?data:row));setEdit(null);setNotice('Bestemmingsland opgeslagen.')}catch(e){setFormError(e instanceof Error?e.message:'Opslaan is niet gelukt.')}finally{setSaving(false)}}
 return <section className="panel historical-register">
  <div className="register-head"><div><span className="section-kicker">{t('GEÏMPORTEERDE HISTORIE')}</span><h2>{t('Alle historische opzeggingen')}</h2><p>{t('Wijs iedere historische case toe aan het land waar de klant naartoe verhuisde.')}</p></div><button className="action secondary" onClick={exportCsv} disabled={!filtered.length}><Download size={17}/>{t('Exporteer selectie')}</button></div>
  <div className="history-assignment-progress"><MapPin size={17}/><strong>{assigned}</strong> {t('van')} {rows.length} {t('cases toegewezen aan een land')}</div>
  <div className="register-tools"><div className="register-filter"><Search size={18}/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} aria-label={t('Historische cases zoeken')} placeholder={t('Zoek installatienummer, bron, status, type of land')}/></div><Select value={destination} onValueChange={value=>{setDestination(value);setPage(1)}}><SelectTrigger className="history-country-filter" aria-label={t('Filter op bestemmingsland')}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ALL">{t('Alle bestemmingen')}</SelectItem><SelectItem value="UNASSIGNED">{t('Nog niet toegewezen')}</SelectItem>{Object.entries(countries).map(([code,name])=><SelectItem key={code} value={code}>{t(name)}</SelectItem>)}</SelectContent></Select></div>
  {notice&&<div className="notice" role="status">{t(notice)}</div>}{error&&<div className="error-banner" role="alert"><AlertCircle size={16}/>{t(error)}</div>}
  <div className="list-summary">{loading?t('Cases laden…'):t('{a} van {b} cases',{a:filtered.length,b:rows.length})}</div>
  {!!visible.length&&<Table className="case-table historical-table"><TableHeader><TableRow>{['INSTALLATIE','AANVRAAG','GESLOTEN','BRON','TYPE','UITKOMST','STATUS','DAGEN','BESTEMMING','ACTIE'].map(key=><TableHead key={key}>{t(key)}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(row=><TableRow key={row.id}><TableCell><strong className="customer-name">{row.installationNumber}</strong></TableCell><TableCell>{date(row.requestDate)}</TableCell><TableCell>{date(row.closedDate)}</TableCell><TableCell>{row.source}</TableCell><TableCell>{t(row.customerType)}</TableCell><TableCell><span className="status status-NO_SALE">{/not retained/i.test(row.result)?t('Niet behouden'):row.result||'—'}</span></TableCell><TableCell>{row.cancelStatus==='CANCELLED'?t('Geannuleerd'):t(row.cancelStatus||'Niet ingevuld')}</TableCell><TableCell>{row.daysToClose}</TableCell><TableCell>{row.destinationCountry?<span className="destination-badge">{row.destinationCountry} · {t(countries[row.destinationCountry])}</span>:<span className="destination-empty">{t('Niet toegewezen')}</span>}</TableCell><TableCell><button className="edit-button" aria-label={t('Bestemmingsland voor case {case} bewerken',{case:row.installationNumber})} onClick={()=>{setEdit({...row});setFormError('')}}><Pencil size={16}/></button></TableCell></TableRow>)}</TableBody></Table>}
  {!loading&&!visible.length&&!error&&<div className="empty-state"><strong>{t('Geen cases gevonden')}</strong><p>{t('Probeer een andere zoekterm.')}</p></div>}
  {pages>1&&<nav className="register-pagination flex items-center justify-center gap-4" aria-label={t('Historische cases')}><button className="action secondary" disabled={page===1} onClick={()=>setPage(page-1)}>{t('Vorige')}</button><span>{page} / {pages}</span><button className="action secondary" disabled={page===pages} onClick={()=>setPage(page+1)}>{t('Volgende')}</button></nav>}
  <p className="register-footer">{t('De oorspronkelijke brongegevens blijven bewaard. Het bestemmingsland is een aanvulling die je in de Hub vastlegt.')}</p>
  <Dialog open={!!edit} onOpenChange={open=>{if(!open)setEdit(null)}}><DialogContent className="case-dialog"><DialogHeader><DialogTitle>{t(admin?'Case bewerken':'Bestemmingsland toewijzen')}</DialogTitle><DialogDescription>{edit?t('Installatie {case}',{case:edit.installationNumber}):t('Historische cases')}</DialogDescription></DialogHeader>{edit&&<form onSubmit={save}>
   <label className="field"><span>{t('Bestemmingsland')}</span><Select value={edit.destinationCountry||'UNASSIGNED'} onValueChange={value=>setEdit({...edit,destinationCountry:value==='UNASSIGNED'?'':value})}><SelectTrigger className="field-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="UNASSIGNED">{t('Nog niet toegewezen')}</SelectItem>{Object.entries(countries).map(([code,name])=><SelectItem key={code} value={code}>{t(name)}</SelectItem>)}</SelectContent></Select></label>
   {admin&&<div className="form-grid history-admin-fields">{Object.entries(columns).map(([key,label])=><label key={key} className="field"><span>{t(label)}</span><input required={['installationNumber','requestDate','closedDate','daysToClose'].includes(key)} type={key.endsWith('Date')?'date':key==='daysToClose'?'number':'text'} readOnly={key==='daysToClose'} min={key==='daysToClose'?0:undefined} value={edit[key as keyof typeof columns]} onChange={e=>{const next={...edit,[key]:e.target.value};const days=(Date.parse(next.closedDate)-Date.parse(next.requestDate))/86400000;next.daysToClose=Number.isFinite(days)?Math.max(0,Math.round(days)):0;setEdit(next)}}/></label>)}</div>}
   {formError&&<p className="form-error" role="alert">{t(formError)}</p>}<div className="form-actions"><button type="button" className="action secondary" onClick={()=>setEdit(null)}>{t('Annuleren')}</button><button type="submit" disabled={saving} className="action primary">{t(saving?'Bezig met opslaan…':'Bestemmingsland opslaan')}</button></div>
  </form>}</DialogContent></Dialog>
 </section>
}
