'use client';
import {useState,type FormEvent} from 'react';
import {LockKeyhole,ArrowRight,ShieldCheck,Globe2,CheckCircle2} from 'lucide-react';
import {useSite,LanguagePicker} from './site-provider';
export default function Login({admin=false}:{admin?:boolean}){
 const {t,settings}=useSite();const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{const response=await fetch(admin?'/api/admin/access':'/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error||'Inloggen is niet gelukt.');location.reload()}catch(e){setError(e instanceof Error?e.message:'Inloggen is niet gelukt.');setCode('')}finally{setBusy(false)}}
 return <main className="entry-page"><header className="entry-header"><img src={settings.logoUrl} alt="Verisure"/><LanguagePicker/></header><div className="entry-grid"><section className="entry-form"><span className="eyebrow">{t(admin?'Beheerderslogin':'INTERNATIONALE VERHUIZINGEN')}</span><h1>{t(admin?'Beheer':'Welkom terug.')}</h1><p className="entry-description">{t(admin?'Log in om inhoud, vormgeving en gegevens te beheren.':'Log in om cases en resultaten bij te werken.')}</p><form onSubmit={submit} className="login-form"><label htmlFor="access-code">{t('Toegangscode')}</label><div className="login-input"><LockKeyhole size={19}/><input id="access-code" type="password" autoComplete="current-password" value={code} onChange={e=>setCode(e.target.value)} required autoFocus placeholder={t('Vul je toegangscode in')}/></div>{error&&<p className="form-error" role="alert">{t(error)}</p>}<button className="action primary" type="submit" disabled={busy||!code.trim()}>{t(busy?'Controleren…':admin?'Inloggen':'Open jouw werkplek')}<ArrowRight size={18}/></button></form><p className="entry-security"><ShieldCheck size={17}/>{t('Beveiligde toegang voor het Verisure-team')}</p><a className="entry-admin" href={admin?'/':'/admin'}>{t(admin?'Terug naar teamlogin':'Beheerderslogin')}<ArrowRight size={14}/></a></section><aside className="entry-story"><span className="entry-badge">{t('Pilot · België, Duitsland & Nederland')}</span><h2>{t('Samen behouden. Over grenzen heen.')}</h2><p>{t('Eén plek voor internationale verhuizingen. Van de eerste overdracht tot het resultaat in het nieuwe land.')}</p><div className="journey-card"><div className="journey-icon"><Globe2 size={26}/></div><strong>{t('International Move Hub')}</strong>{['Nederland coördineert','Het ontvangende land volgt op','Samen inzicht in resultaat'].map((key,i)=><div className="journey-step" key={key}><span>{String(i+1).padStart(2,'0')}</span><p>{t(key)}</p><CheckCircle2 size={18}/></div>)}</div><div className="entry-bottom">VERISURE <span>INTERNATIONAL MOVE HUB</span></div></aside></div></main>
}
