import { NextResponse } from 'next/server';
import { env } from 'cloudflare:workers';
import { hasAccess } from '@/app/access';
import { z } from 'zod';
import {caseSchema,normalizeCase,deadlineFor} from '@/lib/move-cases';
import {sameOrigin} from '@/server/settings';
function db(){if(!env.DB)throw new Error('Database unavailable');return env.DB}
export async function GET(request:Request){const authorized=await hasAccess();if(!authorized)return NextResponse.json({error:'Log in om cases te bekijken.'},{status:401});try{const data=await db().prepare(new URL(request.url).searchParams.get('receiving')==='1'?"SELECT * FROM cases WHERE consent='Yes' AND sent_at IS NOT NULL AND sent_at<>'' ORDER BY created_at DESC":'SELECT * FROM cases ORDER BY created_at DESC').all();return NextResponse.json(data.results)}catch{return NextResponse.json({error:'Cases zijn tijdelijk niet beschikbaar.'},{status:503})}}
export async function POST(request:Request){const authorized=await hasAccess();if(!authorized)return NextResponse.json({error:'Log in om een case op te slaan.'},{status:401});if(!sameOrigin(request))return NextResponse.json({error:'Ongeldige aanvraag.'},{status:403});let data;try{data=normalizeCase(caseSchema.parse(await request.json()))}catch(e){return NextResponse.json({error:e instanceof z.ZodError?e.issues[0]?.message:'Ongeldige invoer.'},{status:400})}const id=crypto.randomUUID();const now=new Date().toISOString();const deadline=deadlineFor(now,data.preferredContactAt);try{await db().prepare(`INSERT INTO cases (id,origin_country,destination_country,customer_name,phone,email,nl_owner,receiving_owner,status,consent,consent_at,consent_version,move_date,preferred_contact_at,created_at,sent_at,sla_deadline,first_contact_at,contact_outcome,reached,interested,appointment_at,installed,installed_at,estimated_revenue,no_sale_reason,description,retention_until,updated_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,data.originCountry,data.destinationCountry,data.customerName,data.phone,data.email,data.nlOwner,data.receivingOwner,data.status,data.consent,data.consentAt||null,data.consentVersion||null,data.moveDate||null,data.preferredContactAt||null,now,data.sentAt||null,deadline,data.firstContactAt||null,data.contactOutcome||null,data.reached,data.interested,data.appointmentAt||null,data.installed,data.installedAt||null,data.estimatedRevenue??null,data.noSaleReason||null,data.description||null,data.retentionUntil||null,now,'Team').run();return NextResponse.json({id},{status:201})}catch{return NextResponse.json({error:'Opslaan is niet gelukt. Probeer het opnieuw.'},{status:503})}}
